# Generated by Django 3.1.5 on 2022-05-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_wine_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='visibility',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='wine',
            name='visibility',
            field=models.BooleanField(default=1),
        ),
    ]
