# Generated by Django 3.1.5 on 2022-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_wine_block_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='year',
            field=models.CharField(default=2012, max_length=50),
            preserve_default=False,
        ),
    ]
