# Generated by Django 5.2.17 on 2026-09-24 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received', to='backend.actor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent', to='backend.actor'),
        ),
        migrations.AddField(
            model_name='wine',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='backend.actor'),
        ),
        migrations.AddField(
            model_name='wine',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
