# Generated by Django 5.2.17 on 2026-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_on_chain_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
