# Generated by Django 3.1.5 on 2022-04-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=100)),
                ('variety_name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5)),
                ('alcohol', models.CharField(max_length=5)),
                ('brand_name', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=200)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backend.wine')),
            ],
        ),
    ]
