# Generated by Django 3.1.5 on 2022-04-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='block_id',
        ),
    ]
